### PR TITLE
[android] Adds ConversionUtil#toList helper, w/ array props conversion

### PR DESCRIPTION
**Pull request by notjosh**
We couldn't send arrays over the bridge on Android (haaa). So, I spent a few mins on the Googles, and [this commit](https://github.com/facebook/react-native/commit/bc0717c6cc56fe0a9a7c066c9f8bf1ab2450bb54) does what we need, so I've pulled it over.

```js
Navigator.present('ScreenOne', {
    someArrayOfNumbers: [
        1, 2, 3,
    ],
    someArrayOfObjects: [
        { name: 'foo' }, { name: 'bar' },
    ],
    someObjectWithArrayOfNumbers: {
        value: [
        1, 2, 3,
        ],
    },
    someOjectWithArrayOfObjects: {
        value: [
        { name: 'foo' }, { name: 'bar' },
        ],
    },
    someObject: {
        value: 'foo',
        another: 'bar',
    },
    strings: 'foo',
    bools: true,
    numbers: 123,
    nulls: null,
})
```

->

```
I/ReactNativeJS: Running application "ScreenOne" with appParams:{
  "initialProps":{
    "someOjectWithArrayOfObjects":{"value":[{"name":"foo"},{"name":"bar"}]},
    "someObjectWithArrayOfNumbers":{"value":[1,2,3]},
    "nulls":null,
    "bools":true,
    "someArrayOfNumbers":[1,2,3],
    "someArrayOfObjects":[{"name":"foo"},{"name":"bar"}],
    "someObject":{"value":"foo","another":"bar"},
    "nativeNavigationInstanceId":"ScreenOne_fragment_3",
    "strings":"foo",
    "numbers":123
},"rootTag":21}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
```

✅

### CODE REVIEW

**Comment by notjosh** [comment]
cc @skeie

**Review by henrikpersson — APPROVED** [review]
Sweet

**Comment by skeie** [comment]
Works like a charm.

**Comment by skeie** [comment]
@notjosh 
Could you delete the branch if everything is ok?

AKA PUSH THE BUTTON

 

image

**Comment by notjosh** [comment]
💥

**Pull request merged**
