### PR TITLE
Emit onLeftPress when BACK button is pressed

### PR DESCRIPTION
**Pull request by henrikpersson**

### CODE REVIEW

**Comment by notjosh** [comment]
What's the use case here?

**Comment by skeie** [comment]
@notjosh 
https://trello.com/c/KUSPHxke/2874-payslip-if-you-go-back-from-take-a-new-photo-if-the-first-one-fails-should-not-display-uploading-screen-again-but-rather-questio

https://trello.com/c/CbNW8irg/2873-payslip-if-you-go-back-from-payslip-form-after-uploading-you-should-not-see-the-uploading-page-but-rather-the-question-screen

Since we're talking about switching to `wix` in the near future. It does not make sense to spend to much time fixing the issue with this navigation.  So the proposed solution to the problem is to let the JS it.

We're open to other solutions if you have one ;>

**Comment by notjosh** [comment]
Is the existing `onDisappear` callback not enough?

(Not opposed to this at all, just trying to actually understand the use case and how you'd use it)

**Comment by skeie** [comment]
The `onDisappear` is also called if the right button is clicked. I would love to spend 5 minutes with you and draw this out. Could be that there is a better approach to this.

**Comment by skeie** [comment]
No need for this anymore. Sorry @henrikpersson  ;<

**Pull request closed without merging**
