### PR TITLE
commented fragment detach code to make state save work

### PR DESCRIPTION
**Pull request by zoe00**

### CODE REVIEW

**Comment by skeie** [comment]
This works for the payslip and commute modal as well? And the back button works with this? Why is that code there in the first place?

**Comment by zoe00** [comment]
> This works for the payslip and commute modal as well? 

For payslip yes, commute, what section exactly?

> And the back button works with this?

yes, surprisingly yes 😀

> Why is that code there in the first place?

Only God and the developer knows 😛

**Comment by skeie** [comment]
Cool 👍

**Review by skeie — COMMENTED** [review]
LGTM.
Let's wait for @henrikpersson since I don't know how fragments work

**Review by henrikpersson — APPROVED** [review]
Nice, tested it and seems to work. Hope this won't add any other sneaky bugs 😈

**Pull request merged**
